name: Build and Publish

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test_and_build:
    environment: pypi
    permissions:
      # IMPORTANT: this permission is mandatory for Trusted Publishing
      id-token: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Set up uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.14"
          enable-cache: true

      - name: Sync dependencies
        run: uv sync --locked

      - name: Run Ruff
        run: uv run ruff check --fix .

      - name: Run Pytest
        run: uv run pytest

      - name: Build package
        run: uv build

      - name: Publish to PyPI
        run: uv publish
